hashtag_mappings = {
    "belarus":
    {
        "belarus",
        "minsk",
        "lukashenko",
        "belarusian",
        "belarusians",
        "bielorussia"
    },
    "biden":
    {
        "biden",
        "joebiden",
        "bidenisafailure",
        "bidenisadisgrace",
        "potus",
        "bidenswar"
    },
    "crypto":
    {
        "bitcoin",
        "nft",
        "crypto",
        "btc",
        "nfts",
        "cryptocurrency",
        "eth",
        "nftcommunity",
        "blockchain",
        "nftart",
        "dogecoin",
        "nftcollection",
        "nftgiveaway",
        "nftdrop",
        "nftartist",
        "cryptonews",
        "nftcollector",
        "cryptocurrencies"
    },
    "cyber":
    {
        "anonymous",
        "osint",
        "cybersecurity",
        "cyber",
        "cyberattacks",
        "cyberattack",
        "cyberwar"
    },
    "energy":
    {
        "nordstream2",
        "oil",
        "gas",
        "gazprom",
        "energy"
    },
    "eu":
    {
        "eu",
        "europe",
        "ue"
    },
    "israel":
    {
        "israel",
        "israeli"
    },
    "nato":
    {
        "nato",
        "otan"
    },
    "palestine":
    {
        "palestine",
        "freepalestine"
    },
    "putin":
    {
        "putin",
        "stopputin",
        "poutine",
        "istandwithputin",
        "putinwarcriminal",
        "stopputinnow",
        "putinisawarcriminal",
        "putinswar",
        "putinhitler",
        "defeatputin",
        "vladimirputin",
        "kremlin",
        "fckputin",
        "fuckputin",
        "putinwarcrimes",
        "putinsgop",
        "putler",
        "fckptn",
        "putinasesino",
        "путин",
        "stopputinswar",
        "putinatwar",
        "putinskrieg",
        "blockputinwallets",
        "putins",
        "poetin",
        "resistputin",
        "criminalputin",
        "heyputin",
        "killputin",
        "adolfputin"
    },
    "sanctions":
    {
        "swift",
        "sanctions",
        "sanctionrussianow",
        "banrussiafromswift",
        "sanktionen",
        "swiftban"
    },
    "trump":
    {
        "trump",
        "traitortrump",
        "putinspuppet",
        "trumpisarussianasset",
        "maga",
        "donaldtrump",
        "trumptraitor",
        "putinspuppets",
        "trumprussia",
        "traitortrumpputinspuppet",
        "trumpcult",
        "trumpisatraitor"
    },
    "un":
    {
        "un",
        "unga",
        "unitednations",
        "оон"
    },
    "usa":
    {
        "usa",
        "sotu",
        "us",
        "america",
        "gop",
        "sotu2022",
        "stateoftheunion",
        "unitedstates",
        "american"
    },
    "ww3":
    {
        "worldwar3",
        "wwiii",
        "terceraguerramundial",
        "nuclearwar",
        "worldwariii",
        "ww3"
    },
    "zelensky":
    {
        "zelensky",
        "zelenskyy",
        "zelenskiy",
        "volodymyrzelensky",
        "selenskyj",
        "volodymyrzelenskyy",
        "zelenski",
        "presidentzelensky",
        "zelinsky"
    }
}
